version: "3.9"

services:
  proxy:
    image: nginx:latest
    container_name: forward-proxy
    ports:
      - "8080:8080"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - back

  web:
    build: ./web
    container_name: frontend
    ports:
      - "3000:80"
    environment:
      - HTTP_PROXY=http://proxy:8080
      - HTTPS_PROXY=http://proxy:8080

  back:
    build: ./back
    container_name: backend
    ports:
      - "8000:8000"
